name: Tests
on: [push, pull_request]
jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: openknowledge/ckan-dev:2.9
    services:
      solr:
        image: ckan/ckan-solr-dev:2.9
      postgres:
        image: ckan/ckan-postgres-dev:2.9
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3
    steps:
    - uses: actions/checkout@v2
    - name: things
      run: |
        pwd
        ls -la /srv/app/
    - name: install reqs
      run: |
        pip install -r pip-requirements.txt
        pip install -e .
    - name: CKAN?
      run: |
        ckan -c test-ga.ini db init
        ckan -c test-ga.ini user
        ckan -c test-ga.ini harvester initdb

